
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mycompany.cxf.soap.model;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621107
 * 2016-09-22T19:08:32.078+05:30
 * Generated source version: 3.0.4.redhat-621107
 * 
 */

@javax.jws.WebService(
                      serviceName = "PersonService",
                      portName = "PersonServicePort",
                      targetNamespace = "http://model.soap.cxf.mycompany.com/",
                      wsdlLocation = "file:/home/kkakarla/Development/Camel-Fuse-Examples/cxf/cxf-http-server-client-custome-soap-header-bundles%20/cxf-soap-http-client/src/main/resources/wsdl/person.wsdl",
                      endpointInterface = "com.mycompany.cxf.soap.model.PersonService")
                      
public class PersonServicePortImpl implements PersonService {

    private static final Logger LOG = Logger.getLogger(PersonServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.model.PersonService#deletePerson(java.lang.String  id )*
     */
    public com.mycompany.cxf.soap.model.Person deletePerson(java.lang.String id) throws PersonException_Exception    { 
        LOG.info("Executing operation deletePerson");
        System.out.println(id);
        try {
            com.mycompany.cxf.soap.model.Person _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PersonException_Exception("PersonException...");
    }

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.model.PersonService#getPerson(java.lang.String  id )*
     */
    public com.mycompany.cxf.soap.model.Person getPerson(java.lang.String id) throws PersonException_Exception    { 
        LOG.info("Executing operation getPerson");
        System.out.println(id);
        try {
            com.mycompany.cxf.soap.model.Person _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PersonException_Exception("PersonException...");
    }

    /* (non-Javadoc)
     * @see com.mycompany.cxf.soap.model.PersonService#putPerson(com.mycompany.cxf.soap.model.Person  arg0 )*
     */
    public com.mycompany.cxf.soap.model.Person putPerson(com.mycompany.cxf.soap.model.Person arg0) { 
        LOG.info("Executing operation putPerson");
        System.out.println(arg0);
        try {
            com.mycompany.cxf.soap.model.Person _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
