
package org.jboss.fuse.samples;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-06-25T10:11:33.225+01:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
 
public class GreeterServer{

    protected GreeterServer() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GreeterImpl();
        String address = "http://localhost:9101/GreeterService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new GreeterServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(50 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
