
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.jboss.fuse.samples;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.hello_world_soap_http.Greeter;
import org.apache.hello_world_soap_http.UnknownRequestFault;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-06-25T10:11:33.189+01:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */

@javax.jws.WebService(
                      serviceName = "SOAPService",
                      portName = "SoapPort",
                      targetNamespace = "http://apache.org/hello_world_soap_http",
                      endpointInterface = "org.apache.hello_world_soap_http.Greeter")
                      
public class GreeterImpl implements Greeter {

    private static final Logger LOG = Logger.getLogger(GreeterImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apache.hello_world_soap_http.Greeter#greetMe(java.lang.String  requestType )*
     */
    public java.lang.String greetMe(java.lang.String requestType) throws UnknownRequestFault    { 
        LOG.info("Executing operation greetMe");
        LOG.info("Received: " + requestType);
        if (requestType.equals("test")) {
            org.apache.hello_world_soap_http.types.UnknownRequestFault requestFault = 
                new org.apache.hello_world_soap_http.types.UnknownRequestFault();
            requestFault.setRequestType(requestType);
            org.apache.hello_world_soap_http.UnknownRequestFault fault =
                new org.apache.hello_world_soap_http.UnknownRequestFault("Get the unknown request: " + requestType, requestFault);
            throw new RuntimeException("something wrong with user Joe");
        } else {
            java.lang.String _return = "hello " + requestType;
            LOG.info("Sending back: " + _return);
            return _return;
        }
    }
}
